import Testing
import Foundation
@testable import DOUGLAS

@Suite("LLMPluginBuilder Tests")
struct LLMPluginBuilderTests {

    // MARK: - 유효한 JSON → 플러그인 생성

    @Test("webhook 핸들러 → manifest + script 생성")
    func webhookHandler() throws {
        let json = """
        {
            "name": "Slack 알림",
            "description": "작업 완료 시 Slack으로 알림",
            "handlers": {
                "on_room_completed": {
                    "action": "webhook",
                    "url": "https://hooks.slack.com/test"
                }
            }
        }
        """
        let (manifest, scripts) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(manifest.name == "Slack 알림")
        #expect(manifest.description == "작업 완료 시 Slack으로 알림")
        #expect(manifest.handlers?.onRoomCompleted != nil)
        #expect(scripts.count == 1)
        #expect(scripts[0].filename == "on_room_completed.sh")
        #expect(scripts[0].content.contains("curl"))
        #expect(scripts[0].content.contains("hooks.slack.com/test"))
    }

    @Test("notification 핸들러 → osascript 생성")
    func notificationHandler() throws {
        let json = """
        {
            "name": "실패 알림",
            "description": "작업 실패 시 알림",
            "handlers": {
                "on_room_failed": {
                    "action": "notification",
                    "title": "작업 실패",
                    "body": "확인해주세요"
                }
            }
        }
        """
        let (_, scripts) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(scripts[0].content.contains("osascript"))
        #expect(scripts[0].content.contains("작업 실패"))
    }

    @Test("shell 핸들러 → 명령 생성")
    func shellHandler() throws {
        let json = """
        {
            "name": "로그 기록",
            "description": "메시지 수신 시 로그",
            "handlers": {
                "on_message": {
                    "action": "shell",
                    "command": "echo $DOUGLAS_MESSAGE_CONTENT >> ~/log.txt"
                }
            }
        }
        """
        let (manifest, scripts) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(manifest.handlers?.onMessage != nil)
        #expect(scripts[0].content.contains("echo $DOUGLAS_MESSAGE_CONTENT"))
    }

    @Test("복수 핸들러 → 각각 스크립트 생성")
    func multipleHandlers() throws {
        let json = """
        {
            "name": "종합 모니터",
            "description": "완료+실패 모두 알림",
            "handlers": {
                "on_room_completed": {
                    "action": "notification",
                    "title": "완료",
                    "body": "작업 완료"
                },
                "on_room_failed": {
                    "action": "webhook",
                    "url": "https://example.com/fail"
                }
            }
        }
        """
        let (manifest, scripts) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(manifest.handlers?.onRoomCompleted != nil)
        #expect(manifest.handlers?.onRoomFailed != nil)
        #expect(scripts.count == 2)
    }

    @Test("config 필드 포함")
    func withConfig() throws {
        let json = """
        {
            "name": "API 연동",
            "description": "API 연동 플러그인",
            "handlers": {
                "on_room_completed": { "action": "webhook", "url": "https://api.test" }
            },
            "config": [
                { "key": "api_token", "label": "API 토큰", "secret": true, "placeholder": "sk-..." }
            ]
        }
        """
        let (manifest, _) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(manifest.config?.count == 1)
        #expect(manifest.config?[0].key == "api_token")
        #expect(manifest.config?[0].secret == true)
    }

    // MARK: - 에러 케이스

    @Test("빈 name → 에러")
    func emptyName() {
        let json = """
        { "name": "", "description": "test", "handlers": { "on_room_completed": { "action": "webhook", "url": "https://test" } } }
        """
        #expect(throws: LLMPluginBuilderError.self) {
            try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        }
    }

    @Test("핸들러 없음 → 에러")
    func noHandlers() {
        let json = """
        { "name": "빈 플러그인", "description": "test" }
        """
        #expect(throws: LLMPluginBuilderError.self) {
            try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        }
    }

    @Test("잘못된 JSON → 에러")
    func invalidJSON() {
        let json = "{ invalid json }"
        #expect(throws: Error.self) {
            try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        }
    }

    // MARK: - ID 자동 생성

    @Test("id 미지정 시 자동 생성")
    func autoGeneratedID() throws {
        let json = """
        {
            "name": "테스트 플러그인",
            "description": "테스트",
            "handlers": { "on_room_completed": { "action": "notification", "title": "완료" } }
        }
        """
        let (manifest, _) = try LLMPluginBuilder.buildPlugin(jsonSpec: json)
        #expect(manifest.id.hasPrefix("custom-"))
        #expect(!manifest.id.isEmpty)
    }
}
